services:
  web:
    image: ${IMAGE_TAG}
    container_name: qpfrontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3007:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
    networks:
      - quidpath_network

networks:
  quidpath_network:
    name: prod_quidpath_network
    driver: bridge
    # Docker Compose will create this network if it doesn't exist
    # or reuse it if another service already created it
